devtools::install_github(repo = "r-net-tools/net.security")
library(net.security)
View(cpes)
View(cves)
str(cves)
head(cves$cvss)
head(cves$cpe.software)
jsonlite::fromJSON(cves$cpe.softwar[3])
class(cves$cpe.softwar[3])
jsonlite::fromJSON(as.character(cves$cpe.softwar[3]))
